import React from 'react'

export const metadata = {
  title: 'Project',
  description: 'Generated by Next.js',
}
const Explayout = ({children}) => {
  return (
    <div className='h-[calc(100vh-144px)] overflow-hidden overflow-y-auto bg-gray-200'>
        {children}
    </div>
  )
}

export default Explayout