import "./globals.css"
import React from "react"
import Footer from "../components/footer/Footer"
import Header from "../components/header/Header"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayoutPage({ children }) {
    return (
        <html lang="en">
            <body>
                <Header />
                <div className="layout-container">
                    <aside className="sidebar">
                        <iframe
                            src="https://chat-with-resume.streamlit.app/?embedded=true"
                            title="Streamlit App"
                            frameBorder="0"
                            allowFullScreen
                            className="streamlit-iframe"
                        ></iframe>
                    </aside>
                    <main className="main-content">
                        {children}
                    </main>
                </div>
                <Footer />
            </body>
        </html>
    )
}
