import "./globals.css"
import React from "react"
import Footer from "../components/footer/Footer"
import Header from "../components/header/Header"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayoutPage({
    children,
}) {
    return (
        <html lang="en">
            <body className="bg-white ">
                <Header/>
                {children}
                <Footer />
            </body>
        </html>
    )
}